# Generated by Django 2.2.5 on 2019-09-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_stat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Question text')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Question text')),
                ('type', models.IntegerField(choices=[(1, '1 выбор'), (2, 'много'), (3, 'текст')], verbose_name='Тип вопроса')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stat.Quiz', verbose_name='Вопросы')),
            ],
        ),
        migrations.CreateModel(
            name='VoteAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30, verbose_name='Ответ')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='VoteQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Текст вопроса')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Изображение')),
                ('time_begin', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('time_end', models.DateTimeField(auto_now=True, verbose_name='Время окончания')),
            ],
        ),
        migrations.CreateModel(
            name='VoteUsersAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='Идентификатор пользователя')),
                ('vote_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stat.VoteAnswer', verbose_name='Ответ пользователя')),
            ],
        ),
        migrations.AddField(
            model_name='voteanswer',
            name='vote_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stat.VoteQuestion', verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='QuizUsersAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=30, verbose_name='Ответ пользователя')),
                ('quiz_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stat.QuizAnswer', verbose_name='Ответ')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stat.QuizQuestion', verbose_name='Вопрос')),
            ],
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='quiz_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_stat.QuizQuestion', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='data_stat.VoteAnswer', verbose_name='Вопросы'),
        ),
    ]
