# Generated by Django 2.2.5 on 2019-09-28 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_stat', '0003_auto_20190928_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='preamble',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quiz', to='data_stat.VoteAnswer', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='quiz_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='data_stat.QuizQuestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qquestions', to='data_stat.Quiz', verbose_name='Вопросы'),
        ),
        migrations.AlterField(
            model_name='voteanswer',
            name='vote_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='data_stat.VoteQuestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='votequestion',
            name='preamble',
            field=models.TextField(blank=True),
        ),
    ]
